"""API数据传输对象层（DTO）"""

from app.schemas.auth import (
    Token,
    SessionResponse,
    TokenResponse,
    UserCreate,
    UserResponse,
)
from app.schemas.common import Location
from app.schemas.agent import (
    AgentContext,
    TravelContext,
    CustomAgentState,
    TaskItem,
    SubAgentResult,
    TravelPlannerState,
    TravelPlannerOutput,
)
from app.schemas.travel import (
    TripRequest,
    POISearchRequest,
    RouteRequest,
    Attraction,
    Meal,
    Hotel,
    Budget,
    DayPlan,
    TripPlan,
    TripPlanResponse,
    PlanResult,
    TaskPlan,
)
from app.schemas.weather import (
    LocationInfo,
    QWeatherInfo,
    AirQualityInfo,
    TravelWeatherData,
    AmapWeatherInfo,
    POIInfo,
)

__all__ = [
    "Token",
    "SessionResponse",
    "TokenResponse",
    "UserCreate",
    "UserResponse",
    "Location",
    "AgentContext",
    "TravelContext",
    "CustomAgentState",
    "TaskItem",
    "SubAgentResult",
    "TravelPlannerState",
    "TravelPlannerOutput",
    "TripRequest",
    "POISearchRequest",
    "RouteRequest",
    "Attraction",
    "Meal",
    "Hotel",
    "Budget",
    "DayPlan",
    "TripPlan",
    "TripPlanResponse",
    "PlanResult",
    "TaskPlan",
    "LocationInfo",
    "QWeatherInfo",
    "AirQualityInfo",
    "TravelWeatherData",
    "AmapWeatherInfo",
    "POIInfo",
]
